// Author: Darren Lester

"use strict";

import {Kana} from "./kana";

export const hiragana = [
	new Kana("あ", "a"),
	new Kana("い", "i"),
	new Kana("う", "u"),
	new Kana("え", "e"),
	new Kana("お", "o"),
	new Kana("か", "ka"),
	new Kana("き", "ki"),
	new Kana("く", "ku"),
	new Kana("け", "ke"),
	new Kana("こ", "ko"),
	new Kana("さ", "sa"),
	new Kana("し", "shi"),
	new Kana("す", "su"),
	new Kana("せ", "se"),
	new Kana("そ", "so"),
	new Kana("た", "ta"),
	new Kana("ち", "chi"),
	new Kana("つ", "tsu"),
	new Kana("て", "te"),
	new Kana("と", "to"),
	new Kana("な", "na"),
	new Kana("に", "ni"),
	new Kana("ぬ", "nu"),
	new Kana("ね", "ne"),
	new Kana("の", "no"),
	new Kana("は", "ha"),
	new Kana("ひ", "hi"),
	new Kana("ふ", "fu"),
	new Kana("へ", "he"),
	new Kana("ほ", "ho"),
	new Kana("ま", "ma"),
	new Kana("み", "mi"),
	new Kana("む", "mu"),
	new Kana("め", "me"),
	new Kana("も", "mo"),
	new Kana("や", "ya"),
	new Kana("ゆ", "yu"),
	new Kana("よ", "yo"),
	new Kana("ら", "ra"),
	new Kana("り", "ri"),
	new Kana("る", "ru"),
	new Kana("れ", "re"),
	new Kana("ろ", "ro"),
	new Kana("わ", "wa"),
	new Kana("を", "o"),
	new Kana("ん", "n")
];
