"use strict";

import {Kana} from "./kana";

export const katakana = [
	new Kana("ア", "a"),
	new Kana("イ", "i"),
	new Kana("ウ", "u"),
	new Kana("エ", "e"),
	new Kana("オ", "o"),
	new Kana("カ", "ka"),
	new Kana("キ", "ki"),
	new Kana("ク", "ku"),
	new Kana("ケ", "ke"),
	new Kana("コ", "ko"),
	new Kana("サ", "sa"),
	new Kana("シ", "shi"),
	new Kana("ス", "su"),
	new Kana("セ", "se"),
	new Kana("ソ", "so"),
	new Kana("タ", "ta"),
	new Kana("チ", "chi"),
	new Kana("ツ", "tsu"),
	new Kana("テ", "te"),
	new Kana("ト", "to"),
	new Kana("ナ", "na"),
	new Kana("ニ", "ni"),
	new Kana("ヌ", "nu"),
	new Kana("ネ", "ne"),
	new Kana("ノ", "no"),
	new Kana("ハ", "ha"),
	new Kana("ヒ", "hi"),
	new Kana("フ", "fu"),
	new Kana("ヘ", "he"),
	new Kana("ホ", "ho"),
	new Kana("マ", "ma"),
	new Kana("ミ", "mi"),
	new Kana("ム", "mu"),
	new Kana("メ", "me"),
	new Kana("モ", "mo"),
	new Kana("ヤ", "ya"),
	new Kana("ユ", "yu"),
	new Kana("ヨ", "yo"),
	new Kana("ラ", "ra"),
	new Kana("リ", "ri"),
	new Kana("ル", "ru"),
	new Kana("レ", "re"),
	new Kana("ロ", "ro"),
	new Kana("ワ", "wa"),
	new Kana("ヲ", "wo"),
	new Kana("ン", "n")
];
